spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./db/db
    username:
    password:

logging:
  level:
    com.example.chat: DEBUG

security:
  jwt:
    secret: jwt.super.secret.key
    token-expiration-time-min: 10080 # 7 days